import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs"
import Navbar from "./components/Navbar"
import { Navbar1 } from "./components/Navbar1"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="grid relative min-w-full min-h-screen max-w-2xl bg-gray-900 ">
            <Navbar />
            {children}
            <div>Footer</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
